spring:
  profiles:
    active: -dev


---
#  开发环境
server:
  port: 8201

spring:
  profiles:
    active: dev
  application:
    name: microservice-config-client


eureka:
  client:
    service-url.defaultZone: http:eureka7001.com:7001/eureka

---
#  测试环境
server:
  port: 8202


spring:
  profiles:
    active: test
  application:
    name: microservice-config-client


eureka:
  client:
    service-url.defaultZone: http:eureka7001.com:7001/eureka
